version = 3.7.17

maxColumn = 100

align.preset = more

newlines {
  alwaysBeforeElseAfterCurlyIf = true
  alwaysBeforeMultilineDef = true
}

rewrite {
  rules = [
    RedundantBraces
    RedundantParens
    SortModifiers
  ]
}

runner {
  dialect = scala3
}

