CREATE TABLE EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND (
    SK_S2P_CROSS_CLIENT_SPEND INTEGER NOT NULL,
    SPEND_REPORTING_CURRENCY_NET_AMOUNT DECIMAL(15, 2) NOT NULL,
    SK_COUNTRY INTEGER NOT NULL,
    SK_ACCOUNTING_DATE INTEGER NOT NULL,
    SK_S2P_BUSINESS_PROCESS_OUTSOURCING_CATEGORY INTEGER NOT NULL,
    SK_S2P_BUSINESS_PROCESS_OUTSOURCING_SUPPLIER INTEGER NOT NULL,
    SK_S2P_BUSINESS_PROCESS_OUTSOURCING_CLIENT INTEGER NOT NULL,
    AUDIT_TIMESTAMP TIMESTAMP NOT NULL
) DISTRIBUTE BY HASH (SK_S2P_CROSS_CLIENT_SPEND) IN TS_EPMPROCUREMENT;
ALTER TABLE EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND ADD CONSTRAINT FACT_S2P_CROSS_CLIENT_SPEND_PK PRIMARY KEY (SK_S2P_CROSS_CLIENT_SPEND) ENFORCED;
COMMENT ON TABLE EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND IS 'Combined aggregated spend data fact for internal / external clients.';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.SK_S2P_CROSS_CLIENT_SPEND IS 'Surrogate Key for the table.';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.SPEND_REPORTING_CURRENCY_NET_AMOUNT IS 'Aggregated spend in reporting currency (USD spot rate). Spend in Local currency is converted with the official USD Plan Exchange Rate.';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.SK_COUNTRY IS 'SK to the Geography enterprise dimension.';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.SK_ACCOUNTING_DATE IS 'SK to the Time Gregorian dimension.';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.SK_S2P_BUSINESS_PROCESS_OUTSOURCING_CATEGORY IS 'SK to the BPO Category dimension (for type of goods/services purchased).';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.SK_S2P_BUSINESS_PROCESS_OUTSOURCING_SUPPLIER IS 'SK to the BPO Supplier dimension (for Parent name mapping).';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.SK_S2P_BUSINESS_PROCESS_OUTSOURCING_CLIENT IS 'SK to the BPO Client dimenson (to identify the client the spend belongs to).';
COMMENT ON COLUMN EPM_PROCUREMENT.FACT_S2P_CROSS_CLIENT_SPEND.AUDIT_TIMESTAMP IS 'Last time (UTC) the table was loaded.';

CREATE TABLE EPM_PROCUREMENT.DIM_S2P_SUPPLIER (
    SK_SUPPLIER_NUMBER INT NOT NULL,
    SUPPLIER_UNIQUE_NUMBER VARCHAR(30) NOT NULL,
    VENDOR_LEAD_CLIENT_NUMBER VARCHAR(10) NOT NULL,
    SUPPLIER_MANAGEMENT_NUMBER VARCHAR(50) NOT NULL,
    SUPPLIER_ERP_NUMBER VARCHAR(50) NOT NULL,
    SUPPLIER_ARIBA_NETWORK_NUMBER VARCHAR(50) NOT NULL,
    SUPPLIER_ARIBA_CONTRACT_MANAGEMENT_NUMBER VARCHAR(50) NOT NULL,
    SUPPLIER_NUMBER VARCHAR(50) NOT NULL,
    SUPPLIER_NAME1 VARCHAR(200) NOT NULL,
    SUPPLIER_NAME2 VARCHAR(100) NOT NULL,
    SUPPLIER_NAME3 VARCHAR(100) NOT NULL,
    SUPPLIER_NAME4 VARCHAR(100) NOT NULL,
    SUPPLIER_ADDRESS_STREET VARCHAR(400) NOT NULL,
    SUPPLIER_ADDRESS_REGION_CODE VARCHAR(50) NOT NULL,
    SUPPLIER_ADDRESS_DISTRICT_NAME VARCHAR(50) NOT NULL,
    SUPPLIER_ADDRESS_CITY VARCHAR(100) NOT NULL,
    SUPPLIER_ADDRESS_COUNTRY_CODE VARCHAR(50) NOT NULL,
    SUPPLIER_ADDRESS_ZIP_CODE VARCHAR(50) NOT NULL,
    SUPPLIER_VAT_REGISTRATION_NUMBER VARCHAR(50) NOT NULL,
    SUPPLIER_CENTRAL_POSTING_BLOCK_CODE CHAR(1) NOT NULL,
    SUPPLIER_CENTRAL_PURCHASING_BLOCK_CODE CHAR(1) NOT NULL,
    SUPPLIER_SEGMENTATION_CODE VARCHAR(10) NOT NULL,
    SUPPLIER_RECORD_CREATION_DATE DATE NOT NULL,
    SUPPLIER_DELETE_FLAG CHAR(1) NOT NULL,
    SUPPLIER_RECORD_SOURCE_SYSTEM VARCHAR(10) NOT NULL,
    SUPPLIER_MASTER_DATA_EXTRACT_TIME TIMESTAMP NOT NULL,
    SUPPLIER_DUNNS_ENTITY_NUMBER VARCHAR(200) NOT NULL,
    SUPPLIER_DUNNS_BRANCH_NUMBER VARCHAR(9) NOT NULL,
    SUPPLIER_DUNNS_DOMESTIC_NUMBER VARCHAR(9) NOT NULL,
    SUPPLIER_DUNNS_GLOBAL_NUMBER VARCHAR(9) NOT NULL,
    SUPPLIER_CONTACT_NAME VARCHAR(30) NOT NULL,
    SUPPLIER_CONTACT_PHONE VARCHAR(17) NOT NULL,
    SUPPLIER_CONTACT_EMAIL VARCHAR(30) NOT NULL,
    SUPPLIER_MASTER_RECORD_CREATION_DATE DATE NOT NULL,
    SUPPLIER_ADDRESS_VERIFICATION_DATE DATE NOT NULL,
    SUPPLIER_PO_BOX VARCHAR(10) NOT NULL,
    SUPPLIER_PO_BOX_ZIP_CODE VARCHAR(10) NOT NULL,
    SUPPLIER_IBM_AFFILIATE_FLAG CHAR(1) NOT NULL,
    SUPPLIER_IN_USE_FLAG CHAR(1) NOT NULL,
    SUPPLIER_SOLE_PROPRIETOR_FLAG CHAR(1) NOT NULL,
    SUPPLIER_SUBCONTRACTOR_FLAG CHAR(1) NOT NULL,
    SHARED_SUPPLIER_FLAG CHAR(1) NOT NULL,
    SK_SUPPLIER_MASTER_RECORD_CREATION_DATE INTEGER NOT NULL,
    SK_SUPPLIER_ADDRESS_VERIFICATION_DATE INTEGER NOT NULL,
    SK_SUPPLIER_BANK INTEGER NOT NULL,
    SK_SUPPLIER_ADDRESS_COUNTRY_CODE INTEGER NOT NULL,
    SK_SUPPLIER_RECORD_CREATION_DATE INTEGER NOT NULL,
    SK_SUPPLIER_RECORD_SOURCE_SYSTEM INTEGER NOT NULL,
    SK_SUPPLIER_MANAGEMENT_NUMBER INTEGER NOT NULL,
    SK_SUPPLIER_ERP_NUMBER INTEGER NOT NULL,
    SK_ARIBA_NETWORK_NUMBER INTEGER NOT NULL,
    SK_SUPPLIER_CONTRACT_MANAGEMENT_NUMBER INTEGER NOT NULL,
    SK_S2P_SUPPLIER_HIERARCHY INTEGER NOT NULL,
    SK_SUPPLIER_ENTITY_DUNS_ID INTEGER NOT NULL,
    SK_LAST_RECORD_CHANGE_DATE INTEGER NOT NULL,
    AUDIT_TIMESTAMP TIMESTAMP NOT NULL
) DISTRIBUTE BY HASH (SK_SUPPLIER_NUMBER) IN TS_EPMPROCUREMENT;
ALTER TABLE EPM_PROCUREMENT.DIM_S2P_SUPPLIER ADD CONSTRAINT DIM_S2P_SUPPLIER_PK PRIMARY KEY (SK_SUPPLIER_NUMBER) ENFORCED;

----- DATA DICTIONARY -----
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_NUMBER IS 'Main SK to the supplier master record';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_UNIQUE_NUMBER IS 'This id uniquely identifies the supplier in the table and across systems. VLC ID, if no VLC, then the CAAPS vendor ID, if the origin of the supplier record is buy@ibm - and no VLC for the supplier - then SM vendor ID';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.VENDOR_LEAD_CLIENT_NUMBER IS 'Suppliers 10 digit VLC number, this might be the same as Supplier Number if the supplier does not have legacy supplier ID or can be blank if the supplier does not have VLC ID.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_MANAGEMENT_NUMBER IS 'Supplier Management ID that uniquely identifies the supplier in Ariba.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ERP_NUMBER IS 'Supplier number used in Ariba ERP module';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ARIBA_NETWORK_NUMBER IS 'Supplier Ariba Network ID that uniquely identifies the supplier in Ariba Network';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ARIBA_CONTRACT_MANAGEMENT_NUMBER IS 'Supplier Contract Management ID that uniquely identifies the supplier in the Ariba Contract Management module.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_NUMBER IS 'uniquely identifies suppliers for SAP systems, called VLC, Vendor Lead Client,10 digits long, begins with 10, for other source system this might not be unique, for those to be used with country+company code to uniquely identify. Also known as Legacy ID';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_NAME1 IS 'Name the supplier has been registered with in IBM supplier onboarding systems';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_NAME2 IS 'Additional field for longer supplier names';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_NAME3 IS 'Additional field for longer supplier names';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_NAME4 IS 'Additional field for longer supplier names';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ADDRESS_STREET IS 'Street name from the supplier address';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ADDRESS_REGION_CODE IS 'Region code from the supplier address';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ADDRESS_DISTRICT_NAME IS 'District name from the supplier address';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ADDRESS_CITY IS 'City name from the supplier address';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ADDRESS_COUNTRY_CODE IS 'Two character country ISO code from the supplier address';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ADDRESS_ZIP_CODE IS 'ZIP code from the supplier address';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_VAT_REGISTRATION_NUMBER IS 'VAT registration number the supplier provided';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_CENTRAL_POSTING_BLOCK_CODE IS 'Supplier posting block is Y if no invoices can be posted, booked for the supplier regardless the country, company, flag is set centrally and is applicable to all lower levels in the company hierarchy. Value is N if invoices can booked, posted. ';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_CENTRAL_PURCHASING_BLOCK_CODE IS 'Supplier purchasing block is Y if no purchase orders can be created for the supplier regardless the country, company, purchasing organization,Flag is N if purchase orders can be created for the supplier';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_SEGMENTATION_CODE IS 'Sunset process for supplier classification';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_RECORD_CREATION_DATE IS 'Create date for the supplier record.  If unavailabe then it is set to 2222-02-22. Source system logic: If LFA1-ERDATE = blank or 00000000, then use past date 1900-06-04.  Format = yyyy-mm-dd';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_DELETE_FLAG IS 'Central deletion flag is set to Y if the supplier cannot be used for any activity. Source system logic: LFA1-LOEVM where if value = X then populate with Y, else N';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_RECORD_SOURCE_SYSTEM IS 'Representing where the supplier master record is originating from. Typically it is SAPGP0100, however, there are some legacy systems not integrated into the general supplier master data management process.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_MASTER_DATA_EXTRACT_TIME IS 'Date and time when the record was extracted from BDW to SM2K.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_DUNNS_ENTITY_NUMBER IS 'Dun and Bradstreet identifier for the Supplier legal entity';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_DUNNS_BRANCH_NUMBER IS 'Dun and Bradstreet identifier for the Supplier legal entitys branch';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_DUNNS_DOMESTIC_NUMBER IS 'Dun and Bradstreet identifier for the Supplier legal entitys domestic ultimate';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_DUNNS_GLOBAL_NUMBER IS 'Dun and Bradstreet identifier for the Supplier legal entitys global ultimate';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_CONTACT_NAME IS 'Employee name at the supplier side who is the main contact';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_CONTACT_PHONE IS 'Main Contacts phone number';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_CONTACT_EMAIL IS 'Main contacts email address';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_MASTER_RECORD_CREATION_DATE IS 'The first time the suppler record was created in the supplier master';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_ADDRESS_VERIFICATION_DATE IS 'last time the supplier address was verified';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_PO_BOX IS 'Supplier PO Box if any';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_PO_BOX_ZIP_CODE IS 'Supplier Zip code belonging to the PO box';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_IBM_AFFILIATE_FLAG IS 'Showing is the supplier is owned by IBM';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_IN_USE_FLAG IS 'Showing if the supplier entity has PO, Invoice, Contract, soursing event activity';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_SOLE_PROPRIETOR_FLAG IS 'Natural Person Flag from MDG';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SUPPLIER_SUBCONTRACTOR_FLAG IS 'Subcontractor flag from SAP Standard Industry System = 01';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SHARED_SUPPLIER_FLAG IS 'Flag to indicate suppliers that work with Redhat and IBM as well.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_MASTER_RECORD_CREATION_DATE IS 'The first time the suppler record was created in the supplier master';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_ADDRESS_VERIFICATION_DATE IS 'last time the supplier address was verified';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_BANK IS 'Connection to the future Enterprise bank dimension';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_ADDRESS_COUNTRY_CODE IS 'SK To GEO dim via 2-digi ISO country code';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_RECORD_CREATION_DATE IS 'sk to Create date for the supplier record.  If unavailabe then it is set to 2222-02-22.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_RECORD_SOURCE_SYSTEM IS 'sk to Representing where the supplier master record is originating from. Typically it is SAPGP0100, however, there are some legacy systems not integrated into the general supplier master data management process.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_MANAGEMENT_NUMBER IS 'sk to Supplier Management ID that uniquely identifies the supplier in Ariba';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_ERP_NUMBER IS 'sk to Supplier number used in Ariba ERP module';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_ARIBA_NETWORK_NUMBER IS 'sk to Supplier Ariba Network ID that uniquely identifies the supplier in Ariba Network';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_CONTRACT_MANAGEMENT_NUMBER IS 'sk to Supplier Contract Management ID that uniquely identifies the supplier in the Ariba Contract Management module.';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_S2P_SUPPLIER_HIERARCHY IS 'Sk to parent name in respective dimension - e.g. defines all Lenovo entities under the parent name LENOVO';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_SUPPLIER_ENTITY_DUNS_ID IS 'Sk to EPM duns dimension';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.SK_LAST_RECORD_CHANGE_DATE IS 'When the anything on the record was changed';
COMMENT ON COLUMN EPM_PROCUREMENT.DIM_S2P_SUPPLIER.AUDIT_TIMESTAMP IS 'Date and time when the record was loaded to EPM';


CREATE TABLE EPM.DIM_TIME_PERIOD_GREGORIAN (
    SK_DAY INTEGER NOT NULL,
    SK_WEEK_IN_QUARTER_YEAR INTEGER NOT NULL,
    SK_WEEK_IN_YEAR INTEGER NOT NULL,
    SK_MONTH INTEGER NOT NULL,
    SK_QUARTER INTEGER NOT NULL,
    SK_HALF INTEGER NOT NULL,
    CALENDAR_DOMAIN VARCHAR(20) NOT NULL,
    DATE DATE,
    DAY_IN_WEEK_NUMBER VARCHAR(3) NOT NULL,
    DAY_IN_WEEK_NAME VARCHAR(20) NOT NULL,
    WEEK_IN_QUARTER_NUMBER VARCHAR(3) NOT NULL,
    WEEK_IN_QUARTER_NAME VARCHAR(20) NOT NULL,
    WEEK_IN_QUARTER_SHORTNAME VARCHAR(20) NOT NULL,
    WEEK_IN_QUARTER_YEAR VARCHAR(20) NOT NULL,
    WEEK_IN_YEAR VARCHAR(3) NOT NULL,
    MONTH_NUMBER VARCHAR(3) NOT NULL,
    MONTH_SHORTNAME VARCHAR(10) NOT NULL,
    MONTH_IN_YEAR VARCHAR(6) NOT NULL,
    QUARTER_NUMBER VARCHAR(3) NOT NULL,
    QUARTER_SHORTNAME VARCHAR(10) NOT NULL,
    QUARTER_IN_YEAR VARCHAR(10) NOT NULL,
    HALF_NUM VARCHAR(3) NOT NULL,
    HALF_SHORTNAME VARCHAR(10) NOT NULL,
    HALF_IN_YEAR VARCHAR(10) NOT NULL,
    YEAR_NUMBER VARCHAR(4) NOT NULL,
    YEAR_SHORTNAME VARCHAR(10) NOT NULL,
    IS_BUSINESS_DAY BOOLEAN NOT NULL,
    BUSINESS_DAYS_IN_MONTH INTEGER NOT NULL,
    BUSINESS_DAYS_IN_QUARTER INTEGER NOT NULL,
    BUSINESS_DAYS_IN_YEAR INTEGER NOT NULL,
    WEEK_BLACKOUT BOOLEAN NOT NULL,
    MONTH_BLACKOUT BOOLEAN NOT NULL,
    AUDIT_TIMESTAMP TIMESTAMP NOT NULL
)
DISTRIBUTE BY HASH (SK_DAY)
IN TS_EPMEDS;

ALTER TABLE EPM.DIM_TIME_PERIOD_GREGORIAN
ADD CONSTRAINT DIM_TIME_PERIOD_GREGORIAN_PK PRIMARY KEY (SK_DAY) ENFORCED;
