package org.ibm
import cats.effect.*
import org.http4s.*
import org.pwharned.database.derive.{
  PrimaryKeyBinder,
  SelectStatement,
  SqlSelect,
  extractPrimaryKeys
}
import org.pwharned.database.hkd.*
import org.pwharned.database.sql.*
import scala.language.implicitConversions
//tapir
import sttp.tapir.*
import sttp.tapir.server.ServerEndpoint
//
import org.pwharned.database.*

import java.nio.charset.StandardCharsets
import java.util.UUID
import scala.util.Try
// future
import java.util.concurrent.Executors
import scala.concurrent.{ExecutionContext, Future}
import scala.concurrent.duration.DurationInt
//
import org.ibm.models.CurrentTime
import org.ibm.TelCodec.jsonBody
import org.pwharned.config.EnvLoader
import org.pwharned.database.sql.Connection.*
import org.pwharned.json.*
import org.pwharned.json.JsonString.*
import org.pwharned.parse.*
import sttp.tapir.generic.auto.*
import sttp.tapir.query as squery
import html._
import org.ibm.models.ApiError
import org.ibm.authz.OIDCAuthMiddleware
import org.ibm.authz.WxoJwtService
import java.util.Base64
import org.ibm.authz.JwtConfig
object Routes {

  given ExecutionContext =
    ExecutionContext.fromExecutor(Executors.newVirtualThreadPerTaskExecutor())
  given DbTypeMapper        = Db2TypeMapper
  given dialect: SqlDialect = Db2Dialect
  val connectionDetails =
    EnvLoader.loadFromFileOrEnv[ConnectionDetails](".env") match
      case Left(value)  => throw new RuntimeException(value)
      case Right(value) => value
  TrustStoreManager.createTrustStoreFromUrl(
    dbUrl = sys.env.getOrElse(
      "CONNECTIONDETAILS_URL",
      throw new RuntimeException(
        "Environment variable CONNECTIONDETAILS_URL is not set"
      )
    ),
    trustStorePath = "truststore.jks",
    password = "changeit"
  )

  given db: Database = Database.apply(connectionDetails)
  db.createPool(connectionDetails)

  val status = db.pool.healthCheck()
  println(status)

  if (!status.healthy) {
    println("Pool is unhealthy!")
    println("Error: " + status.error)
    println("Root cause: " + status.rootCause)
  }

  implicit def jsoniterEntityEncoder[A <: Product](using
      ser: JsonSerializer[A]
  ): EntityEncoder[IO, A] =
    EntityEncoder
      .byteArrayEncoder[IO]
      .contramap[A](x => ser.serialize(x).getBytes(StandardCharsets.UTF_8))

  implicit def jsoniterEntityDecoder[A <: Product](using
      deser: JsonDeserializer[A]
  ): EntityDecoder[IO, A] =
    EntityDecoder
      .byteArrayDecoder[IO]
      .map { x =>
        scala.util
          .Try {
            deser
              .decode(x, 0)
          }
          .toEither
          .fold(
            throw new RuntimeException("Deserialization failed"),
            { case (x, y) => x }
          )
      }

  val health: ServerEndpoint[Any, IO] = endpoint.get
    .in("health" / "ping")
    .out(stringBody)
    .description("Check if the server is alive and running")
    .serverLogic(x => IO.pure(Right("Ok")))

  given uuidSchema: Schema[java.util.UUID] =
    Schema.string[java.util.UUID].description("UUID string")
  given generatedUuidSchema: Schema[GeneratedPrimaryKey[java.util.UUID]] =
    Schema
      .string[GeneratedPrimaryKey[java.util.UUID]]
      .description("UUID string automatically generated by the database")

  implicit def transformJsonString[T[_[_]] <: Product](
      fut: Future[Try[Iterator[JsonString[Persisted[T]]]]]
  ): IO[Either[ApiError, List[JsonString[Persisted[T]]]]] =
    IO.fromFuture(IO.blocking(fut)).map {
      case scala.util.Success(iter) => Right(iter.toList)
      case scala.util.Failure(ex)   => Left(ApiError(ex.getMessage))
    }

  implicit def transform[T[_[_]]](
      fut: Future[Try[Iterator[Persisted[T]]]]
  ): IO[Either[ApiError, List[Persisted[T]]]] =
    IO.fromFuture(IO.blocking(fut)).map {
      case scala.util.Success(iter) => Right(iter.toList)
      case scala.util.Failure(ex)   => Left(ApiError(ex.getMessage))
    }
  implicit def transformString[T[_[_]]](
      fut: Future[Try[Iterator[String]]]
  ): IO[Either[ApiError, String]] =
    IO.fromFuture(IO.blocking(fut)).map {
      case scala.util.Success(iter) => Right(iter.mkString("[", ",", "]"))
      case scala.util.Failure(ex)   => Left(ApiError(ex.getMessage))
    }

  def endpointForNoInput[T[_[_]] <: Product](
      endpointName: String
  )(using
      db: Database,
      jd: JsonDeserializer[Persisted[T]],
      js: JsonSerializer[Persisted[T]],
      sqls: SqlSelect[Persisted[T]],
      sqlsO: SqlSelect[Optional[T]],
      row: Row[Persisted[T]],
      mapDeser: MapDeserializer[Optional[T]],
      fb: FieldBinder[Optional[T]],
      schema: Schema[Persisted[T]]
  ): ServerEndpoint[Any, IO] = {

    type P = Persisted[T] // T[PersistedField]
    type O = Optional[T]  // T[OptionalField]

    OIDCAuthMiddleware.authenticatedEndpoint.get
      .in("api" / endpointName)
      .in(
        sttp.tapir
          .query[Option[Int]]("limit")
          .description(
            "Limits the result set to N records. Defaults to 10. Use this combined with offset to paginate results."
          )
      )
      .in(
        sttp.tapir
          .query[Option[Int]]("offset")
          .description(
            "Offsets the result set by N records. Defaults to 0. Use this combined with limit to paginate results"
          )
      )
      .out(jsonBody[List[P]])
      .description(endpointName)
      .serverLogic { user => (limit, offset) =>
        transform(
          db.withConnection(
            _.query[P](limit.orElse(Some(10)), offset.orElse(Some(0)))
          )
        )
      }
  }

  def endpointFor[T[_[_]] <: Product](
      endpointName: String,
      description: Option[String] = None
  )(using
      db: Database,
      jd: JsonDeserializer[Persisted[T]],
      js: JsonSerializer[Persisted[T]],
      sqls: SqlSelect[Persisted[T]],
      sqlsO: SqlSelect[Optional[T]],
      row: Row[Persisted[T]],
      mapDeser: MapDeserializer[Optional[T]],
      fb: FieldBinder[Optional[T]],
      schema: Schema[Persisted[T]],
      ep: EndpointInput[Optional[T]]
  ): ServerEndpoint[Any, IO] = {

    type P = Persisted[T] // T[PersistedField]
    type O = Optional[T]  // T[OptionalField]

    val base = OIDCAuthMiddleware.authenticatedEndpoint.get
      .in("api" / endpointName)
      .in(ep)
      .in(
        sttp.tapir
          .query[Option[Int]]("limit")
          .description(
            "Limits the result set to N records. Defaults to 10. Use this combined with offset to paginate results."
          )
      )
      .in(
        sttp.tapir
          .query[Option[Int]]("offset")
          .description(
            "Offsets the result set by N records. Defaults to 0. Use this combined with limit to paginate results"
          )
      )
      .out(jsonBody[List[P]])
      .description(endpointName)
      .serverLogic { user => (params, limit, offset) =>
        if params.productIterator.forall(_ == None) then
          transform(
            db.withConnection(
              _.query[P](limit.orElse(Some(10)), offset.orElse(Some(0)))
            )
          )
        else

          transform(
            db.withConnection {
              _.queryParameterized[O, P](params, limit, offset)
            }
          )
      }
    description match
      case Some(value) => base.description(value)
      case _           => base

  }
  import org.ibm.models.WXOConfig
  val wxoConfig: WXOConfig = WXOConfig.fromEnv
  lazy val embeddedChat: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint
      .in("")
      .out(htmlBodyUtf8)
      .description("Return the web chat interface")
      .serverLogic { user => params =>
        val jwtConfig  = JwtConfig.fromEnvironmentBase64().get
        val jwtService = WxoJwtService(jwtConfig)
        val token: IO[String] =
          jwtService.createJwtToken(user.userInfo, user.token)

        token
          .map { wxoToken =>
            val renderedHtml = html
              .index(
                wxoToken,
                wxoConfig.orchestrationId,
                wxoConfig.hostUrl,
                wxoConfig.agentId,
                wxoConfig.agentEnvironmentId,
                user.userInfo.name.getOrElse(user.userInfo.sub),
                user.userInfo.sub
              )
              .body
            Right(renderedHtml)
          }
      }

  lazy val serverTime: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint
      .in("api" / "what_time_is_it")
      .out(jsonBody[CurrentTime])
      .description(
        "Use this so that you know what time it is. When a user asks questions that use relative time, eg: 'Show me POs from last week' or 'Show me invoices from last year', use this tool first to get the current time, then calculate the correct time based on it. "
      )
      .serverLogic { user => params =>
        val now: String = java.time.Instant.now().toString
        IO.pure(Right(CurrentTime(now)))

      }

}
