package org.ibm
import cats.effect.*
import org.http4s.*
import org.pwharned.database.derive.{
  PrimaryKeyBinder,
  SelectStatement,
  SqlSelect,
  extractPrimaryKeys
}
import org.pwharned.database.hkd.*
import org.pwharned.database.sql.*
import org.pwharned.database.derive._
import scala.language.implicitConversions
//tapir
import sttp.tapir.*
import sttp.tapir.server.ServerEndpoint
//
import org.pwharned.database.*

import java.nio.charset.StandardCharsets
import java.util.UUID
import scala.util.Try
// future
import java.util.concurrent.Executors
import scala.concurrent.{ExecutionContext, Future}
import scala.concurrent.duration.DurationInt
//
import org.ibm.models.CurrentTime
import org.ibm.TelCodec.jsonBody
import org.pwharned.config.EnvLoader
import org.pwharned.database.sql.Connection.*
import org.pwharned.json.*
import org.pwharned.json.JsonString.*
import org.pwharned.parse.*
import sttp.tapir.generic.auto.*
import sttp.tapir.query as squery
import html._
import org.ibm.models.ApiError
import org.ibm.authz.OIDCAuthMiddleware
import org.ibm.authz.WxoJwtService
import java.util.Base64
import org.ibm.authz.JwtConfig

import org.ibm.models._

object Routes {

  given ExecutionContext =
    ExecutionContext.fromExecutor(Executors.newVirtualThreadPerTaskExecutor())
  given DbTypeMapper        = PostgresTypeMapper
  given dialect: SqlDialect = PostgresDialect
  val connectionDetails =
    EnvLoader.loadFromFileOrEnv[ConnectionDetails](".env") match
      case Left(value)  => throw new RuntimeException(value)
      case Right(value) => value
  /*
  TrustStoreManager.createTrustStoreFromUrl(
    dbUrl = sys.env.getOrElse(
      "CONNECTIONDETAILS_URL",
      throw new RuntimeException(
        "Environment variable CONNECTIONDETAILS_URL is not set"
      )
    ),
    trustStorePath = "truststore.jks",
    password = "changeit"
  )
   */
  given db: Database = Database.apply(connectionDetails)
  db.createPool(connectionDetails)

  val status = db.pool.healthCheck()
  println(status)

  if (!status.healthy) {
    println("Pool is unhealthy!")
    println("Error: " + status.error)
    println("Root cause: " + status.rootCause)
  }

  implicit def jsoniterEntityEncoder[A <: Product](using
      ser: JsonSerializer[A]
  ): EntityEncoder[IO, A] =
    EntityEncoder
      .byteArrayEncoder[IO]
      .contramap[A](x => ser.serialize(x).getBytes(StandardCharsets.UTF_8))

  implicit def jsoniterEntityDecoder[A <: Product](using
      deser: JsonDeserializer[A]
  ): EntityDecoder[IO, A] =
    EntityDecoder
      .byteArrayDecoder[IO]
      .map { x =>
        scala.util
          .Try {
            deser
              .decode(x, 0)
          }
          .toEither
          .fold(
            throw new RuntimeException("Deserialization failed"),
            { case (x, y) => x }
          )
      }

  val health: ServerEndpoint[Any, IO] = endpoint.get
    .in("health" / "ping")
    .out(stringBody)
    .description("Check if the server is alive and running")
    .serverLogic(x => IO.pure(Right("Ok")))

  given uuidSchema: Schema[java.util.UUID] =
    Schema.string[java.util.UUID].description("UUID string")
  given generatedUuidSchema: Schema[GeneratedPrimaryKey[java.util.UUID]] =
    Schema
      .string[GeneratedPrimaryKey[java.util.UUID]]
      .description("UUID string automatically generated by the database")

  implicit def transformJsonString[T[_[_]] <: Product](
      fut: Future[Try[Iterator[JsonString[Persisted[T]]]]]
  ): IO[Either[ApiError, List[JsonString[Persisted[T]]]]] =
    IO.fromFuture(IO.blocking(fut)).map {
      case scala.util.Success(iter) => Right(iter.toList)
      case scala.util.Failure(ex)   => Left(ApiError(ex.getMessage))
    }

  implicit def transform[T[_[_]]](
      fut: Future[Try[Iterator[Persisted[T]]]]
  ): IO[Either[ApiError, List[Persisted[T]]]] =
    IO.fromFuture(IO.blocking(fut)).map {
      case scala.util.Success(iter) => Right(iter.toList)
      case scala.util.Failure(ex)   => Left(ApiError(ex.getMessage))
    }
  implicit def transformString[T[_[_]]](
      fut: Future[Try[Iterator[String]]]
  ): IO[Either[ApiError, String]] =
    IO.fromFuture(IO.blocking(fut)).map {
      case scala.util.Success(iter) => Right(iter.mkString("[", ",", "]"))
      case scala.util.Failure(ex)   => Left(ApiError(ex.getMessage))
    }

  def endpointForNoInput[T[_[_]] <: Product](
      endpointName: String
  )(using
      db: Database,
      jd: JsonDeserializer[Persisted[T]],
      js: JsonSerializer[Persisted[T]],
      sqls: SqlSelect[Persisted[T]],
      sqlsO: SqlSelect[Optional[T]],
      row: Row[Persisted[T]],
      mapDeser: MapDeserializer[Optional[T]],
      fb: FieldBinder[Optional[T]],
      schema: Schema[Persisted[T]]
  ): ServerEndpoint[Any, IO] = {

    type P = Persisted[T] // T[PersistedField]
    type O = Optional[T]  // T[OptionalField]

    OIDCAuthMiddleware.authenticatedEndpoint.get
      .in("api" / endpointName)
      .in(
        sttp.tapir
          .query[Option[Int]]("limit")
          .description(
            "Limits the result set to N records. Defaults to 10. Use this combined with offset to paginate results."
          )
      )
      .in(
        sttp.tapir
          .query[Option[Int]]("offset")
          .description(
            "Offsets the result set by N records. Defaults to 0. Use this combined with limit to paginate results"
          )
      )
      .out(jsonBody[List[P]])
      .description(endpointName)
      .serverLogic { user => (limit, offset) =>
        transform(
          db.withConnection(
            _.query[P](limit.orElse(Some(10)), offset.orElse(Some(0)))
          )
        )
      }
  }

  def endpointForPost[T[_[_]] <: Product](
      endpointName: String,
      description: Option[String] = None
  )(using
      db: Database,
      jd: JsonDeserializer[New[T]],
      jdp: JsonDeserializer[Persisted[T]],
      ib: InsertBinder[New[T]],
      si: SqlInsert[New[T]],
      js: JsonSerializer[Persisted[T]],
      sqls: SqlSelect[Persisted[T]],
      sqlsO: SqlSelect[Optional[T]],
      row: Row[Persisted[T]],
      mapDeser: MapDeserializer[Optional[T]],
      fb: FieldBinder[Optional[T]],
      schema: Schema[New[T]],
      schemap: Schema[Persisted[T]],
      ep: EndpointInput[Optional[T]]
  ): ServerEndpoint[Any, IO] = {

    type N = New[T]       // T[PersistedField]
    type P = Persisted[T] // T[OptionalField]

    val base = OIDCAuthMiddleware.authenticatedEndpoint.post
      .in(jsonBody[New[T]])
      .in("api" / endpointName)
      .out(jsonBody[List[P]])
      .description(endpointName)
      .serverLogic { user => params =>
        transform(
          db.withConnection {
            _.insert[N, P](params)
          }
        )
      }
    description match
      case Some(value) => base.description(value)
      case _           => base

  }

  def endpointFor[T[_[_]] <: Product](
      endpointName: String,
      description: Option[String] = None
  )(using
      db: Database,
      jd: JsonDeserializer[Persisted[T]],
      js: JsonSerializer[Persisted[T]],
      sqls: SqlSelect[Persisted[T]],
      sqlsO: SqlSelect[Optional[T]],
      row: Row[Persisted[T]],
      mapDeser: MapDeserializer[Optional[T]],
      fb: FieldBinder[Optional[T]],
      schema: Schema[Persisted[T]],
      ep: EndpointInput[Optional[T]]
  ): ServerEndpoint[Any, IO] = {

    type P = Persisted[T] // T[PersistedField]
    type O = Optional[T]  // T[OptionalField]

    val base = OIDCAuthMiddleware.authenticatedEndpoint.get
      .in("api" / endpointName)
      .in(ep)
      .in(
        sttp.tapir
          .query[Option[Int]]("limit")
          .description(
            "Limits the result set to N records. Defaults to 10. Use this combined with offset to paginate results."
          )
      )
      .in(
        sttp.tapir
          .query[Option[Int]]("offset")
          .description(
            "Offsets the result set by N records. Defaults to 0. Use this combined with limit to paginate results"
          )
      )
      .out(jsonBody[List[P]])
      .description(endpointName)
      .serverLogic { user => (params, limit, offset) =>
        if params.productIterator.forall(_ == None) then
          transform(
            db.withConnection(
              _.query[P](limit.orElse(Some(10)), offset.orElse(Some(0)))
            )
          )
        else

          transform(
            db.withConnection {
              _.queryParameterized[O, P](params, limit, offset)
            }
          )
      }
    description match
      case Some(value) => base.description(value)
      case _           => base

  }
  import org.ibm.models.WXOConfig
  val wxoConfig: WXOConfig = WXOConfig.fromEnv
  lazy val embeddedChat: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint
      .in("")
      .out(htmlBodyUtf8)
      .description("Return the web chat interface")
      .serverLogic { user => params =>
        val jwtConfig  = JwtConfig.fromEnvironmentBase64().get
        val jwtService = WxoJwtService(jwtConfig)
        val token: IO[String] =
          jwtService.createJwtToken(user.userInfo, user.token)

        token
          .map { wxoToken =>
            val renderedHtml = html
              .index(
                wxoToken,
                wxoConfig.orchestrationId,
                wxoConfig.hostUrl,
                wxoConfig.agentId,
                wxoConfig.agentEnvironmentId,
                user.userInfo.name.getOrElse(user.userInfo.sub),
                user.userInfo.sub
              )
              .body
            Right(renderedHtml)
          }
      }
  lazy val getUsers = endpointFor[users]("users", Some("Retrieves a list of users"))
  lazy val serverTime: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint
      .in("api" / "what_time_is_it")
      .out(jsonBody[CurrentTime])
      .description(
        "Use this so that you know what time it is. When a user asks questions that use relative time, eg: 'Show me POs from last week' or 'Show me invoices from last year', use this tool first to get the current time, then calculate the correct time based on it. "
      )
      .serverLogic { user => params =>
        val now: String = java.time.Instant.now().toString
        IO.pure(Right(CurrentTime(now)))

      }

  lazy val openAccont: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint
      .in("api" / "openAccount")
      .out(jsonBody[List[Persisted[users]]])
      .description(
        "Use this tool to open a new user account. The User information will be automatically populated from the identity provider. "
      )
      .serverLogic { user => params =>
        import java.util.UUID

        val newUser: New[users] =
          users(
            None,
            UUID.randomUUID().toString(),
            user.userInfo.sub,
            UUID.randomUUID().toString(),
            UUID.randomUUID().toString(),
            "checking",
            10000,
            None,
            None
          );
        transform(db.withConnection(x => x.insert[New[users], Persisted[users]](newUser)))

      }

  lazy val accountInfo: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint
      .in("api" / "accountInfo")
      .out(jsonBody[List[Persisted[users]]])
      .description(
        "Retrieves the account information for a logged in user."
      )
      .serverLogic { user => params =>
        val empty                     = summon[EmptyOptional[users]].empty
        val optional: Optional[users] = empty.copy(name = Some(user.userInfo.sub))
        transform(
          db.withConnection(x => x.queryParameterized[Optional[users], Persisted[users]](optional))
        )

      }

  // Request model - notice NO user_id field
  case class PixKeyRegistrationRequest(
      key_type: String,                  // "email", "phone", "cpf", "cnpj", or "random"
      key_value: String,                 // The actual key value
      is_primary: Option[Boolean] = None // Optional: set as primary key
  )

  object PixKeyRegistrationRequest:
    given JsonDeserializer[PixKeyRegistrationRequest] = JsonDeserializer.derived
    given Schema[PixKeyRegistrationRequest]           = Schema.derived
  lazy val registerPixKey: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint.post
      .in("api" / "pix" / "keys")
      .in(jsonBody[PixKeyRegistrationRequest])
      .out(jsonBody[List[Persisted[pix_keys]]])
      .description(
        "Register a new PIX key for your account. " +
          "The key will automatically be associated with the logged-in user. " +
          "Key types: email, phone, cpf, cnpj, or random. " +
          "Each user can have multiple keys but only one of each type. " +
          "Example: {\"key_type\": \"email\", \"key_value\": \"maria@email.com\"}"
      )
      .serverLogic { user => request =>
        // 1. Lookup the logged-in user's user_id from their sub
        val userQuery = {
          val empty = summon[EmptyOptional[users]].empty
          empty.copy[OptionalField](name = Some(user.userInfo.sub))
        }

        val userResult: IO[Either[ApiError, List[Persisted[users]]]] = transform(
          db.withConnection(
            _.queryParameterized[Optional[users], Persisted[users]](userQuery)
          )
        )

        userResult.flatMap {
          case Left(error) => IO.pure(Left(error))
          case Right(users) =>
            users.headOption match {
              case None => IO.pure(Left(ApiError("User not found. Please open an account first.")))
              case Some(foundUser) =>
                // 2. Create the PIX key with the authenticated user's ID
                val newKey: New[pix_keys] = pix_keys(
                  None,                    // pix_key_id (auto-generated)
                  foundUser.user_id.value, // user_id from authenticated user
                  request.key_type,
                  request.key_value,
                  Some("active"), // status
                  request.is_primary,
                  None, // created_at (database default)
                  None  // updated_at (database default)
                )

                // 3. Insert the PIX key
                transform(
                  db.withConnection {
                    _.insert[New[pix_keys], Persisted[pix_keys]](newKey)
                  }
                )
            }
        }
      }

  /** List all PIX keys for the logged-in user */
  lazy val listMyPixKeys: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint.get
      .in("api" / "pix" / "keys")
      .in(
        sttp.tapir
          .query[Option[String]]("status")
          .description("Filter by status: active, inactive, or pending. Defaults to all statuses.")
      )
      .out(jsonBody[List[Persisted[pix_keys]]])
      .description(
        "List all PIX keys registered to your account. " +
          "Returns keys with their type (email, phone, etc.), value, and status. " +
          "Use this to see which keys you can share for receiving payments."
      )
      .serverLogic { user => statusFilter =>
        // 1. Lookup the logged-in user's user_id from their sub
        val userQuery = {
          val empty = summon[EmptyOptional[users]].empty
          empty.copy[OptionalField](name = Some(user.userInfo.sub))
        }

        val userResult: IO[Either[ApiError, List[Persisted[users]]]] = transform(
          db.withConnection(
            _.queryParameterized[Optional[users], Persisted[users]](userQuery)
          )
        )

        userResult.flatMap {
          case Left(error) => IO.pure(Left(error))
          case Right(users) =>
            users.headOption match {
              case None => IO.pure(Left(ApiError("User not found. Please open an account first.")))
              case Some(foundUser) =>
                // 2. Query PIX keys for this user
                val keysQuery = {
                  val empty = summon[EmptyOptional[pix_keys]].empty
                  empty.copy[OptionalField](
                    user_id = Some(foundUser.user_id.value),
                    status = statusFilter
                  )
                }

                // 3. Return the keys
                transform(
                  db.withConnection(
                    _.queryParameterized[Optional[pix_keys], Persisted[pix_keys]](keysQuery)
                  )
                )
            }
        }
      }

  case class PixKeyLookupResponse(
      key_value: String,
      owner_name: String,
      account_type: String,
      bank: String
  )

  object PixKeyLookupResponse:
    given JsonSerializer[PixKeyLookupResponse] = JsonSerializer.derived
    given Schema[PixKeyLookupResponse]         = Schema.derived

  /** Lookup who owns a PIX key (for sending money) */
  lazy val lookupPixKey: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint.get
      .in("api" / "pix" / "keys" / "lookup")
      .in(
        sttp.tapir
          .query[String]("key_value")
          .description("The PIX key to lookup (email, phone, CPF, etc.)")
      )
      .out(jsonBody[PixKeyLookupResponse])
      .description(
        "Look up who owns a PIX key before sending them money. " +
          "Returns the owner's name and account information. " +
          "Use this to verify you're sending to the right person. " +
          "Example: GET /api/pix/keys/lookup?key_value=maria@email.com"
      )
      .serverLogic { user => keyValue =>
        // 1. Query for the PIX key
        val keyQuery = {
          val empty = summon[EmptyOptional[pix_keys]].empty
          empty.copy[OptionalField](
            key_value = Some(keyValue),
            status = Some("active")
          )
        }

        val keyResult: IO[Either[ApiError, List[Persisted[pix_keys]]]] = transform(
          db.withConnection(
            _.queryParameterized[Optional[pix_keys], Persisted[pix_keys]](keyQuery)
          )
        )

        keyResult.flatMap {
          case Left(error) => IO.pure(Left(error))
          case Right(keys) =>
            keys.headOption match {
              case None => IO.pure(Left(ApiError(s"PIX key not found or inactive: $keyValue")))
              case Some(pixKey) =>
                // 2. Query for the owner's information
                val ownerQuery = {
                  val empty = summon[EmptyOptional[users]].empty
                  empty.copy[OptionalField](user_id = Some(pixKey.user_id))
                }

                val ownerResult: IO[Either[ApiError, List[Persisted[users]]]] = transform(
                  db.withConnection(
                    _.queryParameterized[Optional[users], Persisted[users]](ownerQuery)
                  )
                )

                ownerResult.map {
                  case Left(error) => Left(error)
                  case Right(owners) =>
                    owners.headOption match {
                      case None => Left(ApiError("Owner information not found"))
                      case Some(owner) =>
                        Right(
                          PixKeyLookupResponse(
                            key_value = pixKey.key_value.value,
                            owner_name = owner.name.value,
                            account_type = owner.account_type.value,
                            bank = "Mock PIX Bank"
                          )
                        )
                    }
                }
            }
        }
      }

  case class PixTransferRequest(
      receiver_pix_key: String,
      amount: BigDecimal,
      description: Option[String] = None
  )
  object PixTransferRequest:
    given JsonDeserializer[PixTransferRequest] = JsonDeserializer.derived
    given Schema[PixTransferRequest]           = Schema.derived
  case class PixTransferResponse(
      transaction_id: Int,
      transaction_uuid: String,
      sender_user_id: Int,
      receiver_user_id: Int,
      receiver_name: String,
      amount: BigDecimal,
      status: String,
      created_at: String
  )
  object PixTransferResponse:
    given JsonSerializer[PixTransferResponse] = JsonSerializer.derived
    given Schema[PixTransferResponse]         = Schema.derived
  lazy val makePixTransfer: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint.post
      .in("api" / "pix" / "transfer")
      .in(jsonBody[PixTransferRequest])
      .out(jsonBody[List[Persisted[transactions]]])
      .description(
        "Send money instantly to another user using their PIX key. " +
          "The money will be deducted from your balance and added to the recipient. " +
          "Example: {\"receiver_pix_key\": \"maria@email.com\", \"amount\": 50.00, \"description\": \"Lunch payment\"}"
      )
      .serverLogic { user => request =>
        // 1. Get sender info
        val senderQuery = {
          val empty = summon[EmptyOptional[users]].empty
          empty.copy[OptionalField](name = Some(user.userInfo.sub))
        }

        val senderResult: IO[Either[ApiError, List[Persisted[users]]]] = transform(
          db.withConnection(
            _.queryParameterized[Optional[users], Persisted[users]](senderQuery)
          )
        )

        senderResult.flatMap {
          case Left(error) => IO.pure(Left(error))
          case Right(senders) =>
            senders.headOption match {
              case None =>
                IO.pure(Left(ApiError("Sender account not found. Please open an account first.")))
              case Some(sender) =>
                // 2. Validate balance
                if (sender.balance < request.amount) {
                  IO.pure(
                    Left(
                      ApiError(
                        s"Insufficient balance. Available: R$$${sender.balance}, Required: R$$${request.amount}"
                      )
                    )
                  )
                }
                else {
                  // 3. Lookup receiver by PIX key
                  val keyQuery = {
                    val empty = summon[EmptyOptional[pix_keys]].empty
                    empty.copy[OptionalField](
                      key_value = Some(request.receiver_pix_key),
                      status = Some("active")
                    )
                  }

                  val keyResult: IO[Either[ApiError, List[Persisted[pix_keys]]]] = transform(
                    db.withConnection(
                      _.queryParameterized[Optional[pix_keys], Persisted[pix_keys]](keyQuery)
                    )
                  )

                  keyResult.flatMap {
                    case Left(error) => IO.pure(Left(error))
                    case Right(keys) =>
                      keys.headOption match {
                        case None =>
                          IO.pure(
                            Left(
                              ApiError(s"Receiver PIX key not found: ${request.receiver_pix_key}")
                            )
                          )
                        case Some(pixKey) =>
                          // 4. Get receiver info
                          val receiverQuery = {
                            val empty = summon[EmptyOptional[users]].empty
                            empty.copy[OptionalField](user_id = Some(pixKey.user_id))
                          }

                          val receiverResult
                              : IO[Either[ApiError, List[Persisted[users]]]] = transform(
                            db.withConnection(
                              _.queryParameterized[Optional[users], Persisted[users]](receiverQuery)
                            )
                          )

                          receiverResult.flatMap {
                            case Left(error) => IO.pure(Left(error))
                            case Right(receivers) =>
                              receivers.headOption match {
                                case None => IO.pure(Left(ApiError("Receiver account not found")))
                                case Some(receiver) =>
                                  // 5. Update balances and create transaction in same connection
                                  val transactionUuid = java.util.UUID.randomUUID().toString

                                  val result =
                                    db.withConnection { conn =>
                                      // Update sender balance
                                      val updatedSender = sender.copy[PersistedField](
                                        balance = sender.balance - request.amount
                                      )
                                      conn.update[Persisted[users], Persisted[users]](
                                        updatedSender
                                      )

                                      // Update receiver balance
                                      val updatedReceiver = receiver.copy[PersistedField](
                                        balance = receiver.balance + request.amount
                                      )
                                      conn.update[Persisted[users], Persisted[users]](
                                        updatedReceiver
                                      )

                                      // Create transaction record
                                      val newTransaction: New[transactions] = transactions(
                                        None,
                                        transactionUuid,
                                        sender.user_id.value,
                                        receiver.user_id.value,
                                        request.amount,
                                        "pix_key",
                                        Some(request.receiver_pix_key),
                                        request.description.getOrElse(""),
                                        Some("completed"),
                                        None,
                                        None
                                      )

                                      conn.insert[New[transactions], Persisted[transactions]](
                                        newTransaction
                                      )
                                    }

                                  transform(result)
                              }
                          }
                      }
                  }
                }
            }
        }
      }

  lazy val getTransactionHistory: ServerEndpoint[Any, IO] =
    OIDCAuthMiddleware.authenticatedEndpoint.get
      .in("api" / "pix" / "transactions")
      .in(
        sttp.tapir
          .query[Option[Int]]("limit")
          .description("Limit results (default 10)")
      )
      .in(
        sttp.tapir
          .query[Option[Int]]("offset")
          .description("Offset for pagination (default 0)")
      )
      .out(jsonBody[List[Persisted[transactions]]])
      .description(
        "Get your PIX transaction history. Shows both money you've sent and received. " +
          "Use this to verify transfers completed successfully and track your payment activity. " +
          "Results are ordered by most recent first."
      )
      .serverLogic { user => (limit, offset) =>
        // 1. Get user info
        val userQuery = {
          val empty = summon[EmptyOptional[users]].empty
          empty.copy[OptionalField](name = Some(user.userInfo.sub))
        }

        val userResult: IO[Either[ApiError, List[Persisted[users]]]] = transform(
          db.withConnection(
            _.queryParameterized[Optional[users], Persisted[users]](userQuery)
          )
        )

        userResult.flatMap {
          case Left(error) => IO.pure(Left(error))
          case Right(users) =>
            users.headOption match {
              case None => IO.pure(Left(ApiError("User not found. Please open an account first.")))
              case Some(foundUser) =>
                // 2. Query transactions where user is sender OR receiver
                val txnQuery = {
                  val empty = summon[EmptyOptional[transactions]].empty
                  empty.copy[OptionalField](
                    sender_user_id = Some(foundUser.user_id.value)
                  )
                }

                transform(
                  db.withConnection(
                    _.queryParameterized[Optional[transactions], Persisted[transactions]](
                      txnQuery,
                      limit,
                      offset
                    )
                  )
                )
            }
        }
      }

}
